### ISSUE TITLE
Раздел Payments

### ISSUE THREAD

**Issue by annaofc** [Xandir150/montel_admin#29]
1. Добавить графу примечание
2. Добавить способ оплаты "Hungry Terminal" в Other methods ( для отслеживания денег полученных терминалом, но не зачисленных).

**Comment by annaofc** [comment]
3. Метод оплаты (вывести общую сумму)

**Comment by annaofc** [comment]
Hungry terminal должен быть по каждому терминале

**Comment by Xandir150** [comment]
При ручном внесении будет обязательным комментарий. Наличие комментария является показателем ручного ввода. Кроме этого, у меня в базе фиксируются ручные операции.
Эта информация является служебной, только для устранения проблем.
Думаю, не стоит усложнять. А сбойные мы и так увидим.
