### ISSUE TITLE
Тарифы

### ISSUE THREAD

**Issue by Montel-admin** [Xandir150/montel_admin#3]
Поменять название тарифов в админке

**Comment by Xandir150** [comment]
Оставаил 3 опции
0 = неизвестен
1 = тариф 6
2 = тариф 9
В соответсвии с полседним счётом у кого было меньше 6 (в счетё) стал тариф 6, у кого 6 и более тариф 9
Всех отсутсвующих в счёте и находящихся на неизветсных тарифах - перевёл на 0 (неизвестно)
