### ISSUE TITLE
Время Терминалов

### ISSUE THREAD

**Issue by Montel-admin** [Xandir150/montel_admin#4]
Время не совпадает. В развернутом виде время отображается на час раньше
![Screenshot_2020-11-24-10-51-39-792_com android chrome](https://user-images.githubusercontent.com/74590412/100086884-467f3280-2e4e-11eb-92de-daaabdf6f84e.jpg)

**Comment by Xandir150** [comment]
Время отображается как установлен часовой пояс на телефоне \ компьютере открывшего сайт.
В базе время по гринвичу. Сделано для универсальности, на случай использования в других регионах.
И проверьте как на компьютере. Может переход на зимнее не учли...
